[build]
  command = "npm run build"
  publish = "dist" # (Make sure this matches your build folder, it might be 'build' instead of 'dist')

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://meet-scribe-zw7b.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200